### PR TITLE
add type annotations

### PR DESCRIPTION
**Pull request by mildsunrise**
(I recommend reviewing each commit separately)

adds a bunch of JSDoc comments to the code to
 - document the wire protocol
 - allow the user to type their code
 - typecheck our own code (it's only a few lines more, so just in case)

also some small fixes to README

### CODE REVIEW

**Review by murillo128 — APPROVED** [review]

**Comment by mildsunrise** [comment]
it would be nice to release a new semver minor version when you've got time :)

**Comment by murillo128** [comment]
done `v2.1.5`

**Comment by mildsunrise** [comment]
(btw just in case, the release is up but I noticed you didn't commit the changes to the repo)

**Comment by murillo128** [comment]
should be ok now, right?

**Pull request merged**
